# Installs packages to run edx locally on a single instance
# requires:
#  - group_vars/all
#  - common/tasks/main.yml
#
#  This installs mysql-server-5.5 though
#  in production we use mysql-5.1.62.
#
#  We could install from source instead:
#  http://downloads.mysql.com/archives/mysql-5.1/mysql-5.1.62.tar.gz
#
---
- name: install packages needed for single server
  apt: pkg={{','.join(edxlocal_debian_pkgs)}} install_recommends=yes state=present

- name: create a database for edxapp
  mysql_db: >
    db={{ EDXAPP_MYSQL_DB_NAME }}
    state=present
    encoding=utf8
    login_host={{ EDXAPP_MYSQL_HOST }}
    login_port={{ EDXAPP_MYSQL_PORT }}
    login_user={{ EDXAPP_MYSQL_USER }}
    login_password={{ EDXAPP_MYSQL_PASSWORD }}

- name: create a database for xqueue
  mysql_db: >
    db={{ XQUEUE_MYSQL_DB_NAME }}
    state=present
    encoding=utf8
    login_host={{ XQUEUE_MYSQL_HOST }}
    login_port={{ XQUEUE_MYSQL_PORT }}
    login_user={{ XQUEUE_MYSQL_USER }}
    login_password={{ XQUEUE_MYSQL_PASSWORD }}

- name: create a database for ora
  mysql_db: >
    db={{ ORA_MYSQL_DB_NAME }}
    state=present
    encoding=utf8
    login_host={{ ORA_MYSQL_HOST }}
    login_port={{ ORA_MYSQL_PORT }}
    login_user={{ ORA_MYSQL_USER }}
    login_password={{ ORA_MYSQL_PASSWORD }}

- name: create a database for discern
  mysql_db: >
    db={{ DISCERN_MYSQL_DB_NAME }}
    state=present
    encoding=utf8
    login_host={{ DISCERN_MYSQL_HOST }}
    login_port={{ DISCERN_MYSQL_PORT }}
    login_user={{ DISCERN_MYSQL_USER }}
    login_password={{ DISCERN_MYSQL_PASSWORD }}

- name: install memcached
  apt: pkg=memcached state=present
